name: Scala CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Cache Coursier and node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier
            ~/.ivy2
            ~/.cache/scalablytyped
            .target/scala-2.13/scalajs-bundler/main/node_modules
          key: ${{ runner.os }}-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Test
        run: ./sbt test
